# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_esxclipy', [dirname(__file__)])
        except ImportError:
            import _esxclipy
            return _esxclipy
        if fp is not None:
            try:
                _mod = imp.load_module('_esxclipy', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _esxclipy = swig_import_helper()
    del swig_import_helper
else:
    import _esxclipy
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _esxclipy.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self) -> "PyObject *" : return _esxclipy.SwigPyIterator_value(self)
    def incr(self, n : 'size_t'=1) -> "swig::SwigPyIterator *" : return _esxclipy.SwigPyIterator_incr(self, n)
    def decr(self, n : 'size_t'=1) -> "swig::SwigPyIterator *" : return _esxclipy.SwigPyIterator_decr(self, n)
    def distance(self, *args) -> "ptrdiff_t" : return _esxclipy.SwigPyIterator_distance(self, *args)
    def equal(self, *args) -> "bool" : return _esxclipy.SwigPyIterator_equal(self, *args)
    def copy(self) -> "swig::SwigPyIterator *" : return _esxclipy.SwigPyIterator_copy(self)
    def next(self) -> "PyObject *" : return _esxclipy.SwigPyIterator_next(self)
    def __next__(self) -> "PyObject *" : return _esxclipy.SwigPyIterator___next__(self)
    def previous(self) -> "PyObject *" : return _esxclipy.SwigPyIterator_previous(self)
    def advance(self, *args) -> "swig::SwigPyIterator *" : return _esxclipy.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args) -> "bool" : return _esxclipy.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args) -> "bool" : return _esxclipy.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args) -> "swig::SwigPyIterator &" : return _esxclipy.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args) -> "swig::SwigPyIterator &" : return _esxclipy.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args) -> "swig::SwigPyIterator *" : return _esxclipy.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args) -> "ptrdiff_t" : return _esxclipy.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _esxclipy.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr
    def iterator(self) -> "swig::SwigPyIterator *" : return _esxclipy.StringVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self) -> "bool" : return _esxclipy.StringVector___nonzero__(self)
    def __bool__(self) -> "bool" : return _esxclipy.StringVector___bool__(self)
    def __len__(self) -> "std::vector< std::string >::size_type" : return _esxclipy.StringVector___len__(self)
    def pop(self) -> "std::vector< std::string >::value_type" : return _esxclipy.StringVector_pop(self)
    def __getslice__(self, *args) -> "std::vector< std::string,std::allocator< std::string > > *" : return _esxclipy.StringVector___getslice__(self, *args)
    def __setslice__(self, *args) -> "void" : return _esxclipy.StringVector___setslice__(self, *args)
    def __delslice__(self, *args) -> "void" : return _esxclipy.StringVector___delslice__(self, *args)
    def __delitem__(self, *args) -> "void" : return _esxclipy.StringVector___delitem__(self, *args)
    def __getitem__(self, *args) -> "std::vector< std::string >::value_type const &" : return _esxclipy.StringVector___getitem__(self, *args)
    def __setitem__(self, *args) -> "void" : return _esxclipy.StringVector___setitem__(self, *args)
    def append(self, *args) -> "void" : return _esxclipy.StringVector_append(self, *args)
    def empty(self) -> "bool" : return _esxclipy.StringVector_empty(self)
    def size(self) -> "std::vector< std::string >::size_type" : return _esxclipy.StringVector_size(self)
    def clear(self) -> "void" : return _esxclipy.StringVector_clear(self)
    def swap(self, *args) -> "void" : return _esxclipy.StringVector_swap(self, *args)
    def get_allocator(self) -> "std::vector< std::string >::allocator_type" : return _esxclipy.StringVector_get_allocator(self)
    def begin(self) -> "std::vector< std::string >::iterator" : return _esxclipy.StringVector_begin(self)
    def end(self) -> "std::vector< std::string >::iterator" : return _esxclipy.StringVector_end(self)
    def rbegin(self) -> "std::vector< std::string >::reverse_iterator" : return _esxclipy.StringVector_rbegin(self)
    def rend(self) -> "std::vector< std::string >::reverse_iterator" : return _esxclipy.StringVector_rend(self)
    def pop_back(self) -> "void" : return _esxclipy.StringVector_pop_back(self)
    def erase(self, *args) -> "std::vector< std::string >::iterator" : return _esxclipy.StringVector_erase(self, *args)
    def __init__(self, *args): 
        this = _esxclipy.new_StringVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args) -> "void" : return _esxclipy.StringVector_push_back(self, *args)
    def front(self) -> "std::vector< std::string >::value_type const &" : return _esxclipy.StringVector_front(self)
    def back(self) -> "std::vector< std::string >::value_type const &" : return _esxclipy.StringVector_back(self)
    def assign(self, *args) -> "void" : return _esxclipy.StringVector_assign(self, *args)
    def resize(self, *args) -> "void" : return _esxclipy.StringVector_resize(self, *args)
    def insert(self, *args) -> "void" : return _esxclipy.StringVector_insert(self, *args)
    def reserve(self, *args) -> "void" : return _esxclipy.StringVector_reserve(self, *args)
    def capacity(self) -> "std::vector< std::string >::size_type" : return _esxclipy.StringVector_capacity(self)
    __swig_destroy__ = _esxclipy.delete_StringVector
    __del__ = lambda self : None;
StringVector_swigregister = _esxclipy.StringVector_swigregister
StringVector_swigregister(StringVector)

class EsxcliPy(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, EsxcliPy, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, EsxcliPy, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _esxclipy.new_EsxcliPy(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _esxclipy.delete_EsxcliPy
    __del__ = lambda self : None;
    def Execute(self, *args) -> "int" : return _esxclipy.EsxcliPy_Execute(self, *args)
EsxcliPy_swigregister = _esxclipy.EsxcliPy_swigregister
EsxcliPy_swigregister(EsxcliPy)

# This file is compatible with both classic and new-style classes.


